### ISSUE TITLE
[BUG] increment command messages breaking our official guildelines

### ISSUE THREAD

**Issue by Nabhag8848** [RocketChat/Rocket.Chat.Demo.App#9]
### Description:
- There are several issues which is breaking our chat messages guidelines provided in documentation, when running all `/increment` command (with or without argument). The guideline is as follows (highlighted point).

**EDIT**: UI GUIDELINE: https://developer.rocket.chat/apps-engine/ui-guidelines

![Demo App](https://user-images.githubusercontent.com/65061890/221663074-19b70783-d120-4918-8d95-0f31f28411e3.png)

#### When running `/increment`,  `/increment help` and `/increment NotANumberSomeRandomText`: 
-  the message to the channel has been send by the user which is the account owner of rocketchat and it is persistance so it won't get removed when refresh and can be seen by the other users within room. Which is against the guidelines and this is usually not the ideal behaviour of rocket.chat apps for such behaviour commands. Check **[Fig 9.1]**
#### When running `/increment reset` and  `/increment <number>`
- the message to the channel has been send by the user which is the account owner of rocketchat this is against the guidelines but in this case we must note messages are already persistance and needs to be persistance and as it is and should be visible to other users in the room. Check **[Fig 9.2]**

### To reproduce:
- Run `/increment` command  with all the above case mentioned and check the resulting message.

### Expected behavior:
- when running `/increment`,  `/increment help` and `/increment NotANumberSomeRandomText` message should be send by the AppBot, should not be persistance and should not be visible by the other user of room.
- when running `/increment reset` and  `/increment <number>` message should be send by the AppBot.
 **NOTE:**  should be persistance as it is currently and should also be visible by the other user in the room.

### Actual behavior:

![Screenshot from 2023-02-27 22-56-20](https://user-images.githubusercontent.com/65061890/221670561-5b3c1152-5480-48f5-bf93-5c0dabeae99b.png)

<p align="center"> <b>[Fig. 9.1]</b> </p>

![Screenshot from 2023-02-28 01-40-38](https://user-images.githubusercontent.com/65061890/221673022-a8d83797-da55-4af4-ac72-6766925f1fb2.png)
<p align="center"> <b>[Fig. 9.2]</b> </p>

### Additional context
- [x] Willing to fix this one, waiting for your acknowledgement/assign
- [x] Also do let me know if i misfigured out the feature and do correct me, Thanks.

**Comment by Nabhag8848** [comment]
Hey, @dudanogueira, Do check this and lemme know,

**Comment by dudanogueira** [comment]
Nice!

I believe that the `/increment help` should be a notification, but the output of the `/increment digit` should be a message.

The idea here is to create kind of an "auction mini app". On thing that could be added here, in order to expand on the persistence part, is to make the increment persist per channel.

**Comment by Nabhag8848** [comment]
> Nice!
> 
> I believe that the `/increment help` should be a notification, but the output of the `/increment digit` should be a message.
> 
> The idea here is to create kind of an "auction mini app". On thing that could be added here, in order to expand on the persistence part, is to make the increment persist per channel.

Cool. Thanks!
